#!/bin/bash  
#export 'PS4=\e[1;34m+ ${FUNCNAME:-main}@\e[1;36m${BASH_SOURCE#${BLIB_BASE}/}: \e[0;32m${LINENO}->\e[0m'

#This script checks weither port 22 is open/closed
#According that fact it will determine how to access the cluster
#author@Nataf.



#Bugz:
#1.Supports partially if Cluster is behind  GW!




gssh (){

  gsshFlag=false
  ipFlag=false
  myCluster=""
  accessThrough=""
  accessThroughNum=""
  commandLine=""
  userName=`whoami`
  shiftMyVariable $*
  excecution
  
}

global_ssh (){
  gsshFlag=false
  ipFlag=false
  myCluster=""
  accessThrough=""
  accessThroughNum=""
  commandLine=""
  userName=`whoami`
  shiftMyVariable $*
  excecution

}


#This function receives cluster name & returns if its Harpoon or Not.


shiftMyVariable () {
   
	  if ($(echo $1 | grep "\-" &> /dev/null)); then
		shift
	  fi
              fullClusterName=$1;
              shift;
              commandLine=$*;
}

parseClusterName () {
 
   #In case there is a user name - It seperate is from cluster name
   if ($( echo $fullClusterName | grep "\@" &> /dev/null)); then
        userName=`echo $fullClusterName | awk -F "@" {'print $1'}`
        fullClusterName=`echo $fullClusterName | awk -F "@" {'print $2'}`
        myCluster=$fullClusterName
   fi

   #Test if an IP supplied or HostName
   if [ `echo $fullClusterName | grep -o "\.\|\:" | wc -l` -lt 2 ];then
     #In case there is a cluster name with vip/node/exadmin etc.  - It seperate it from cluster name
     if ($(echo $fullClusterName | grep "\." &> /dev/null)); then
       accessThrough=`echo $fullClusterName | awk -F "." {'print $1'} | rev | cut -c 2- | rev `
       accessThroughNum=`echo $fullClusterName | awk -F "." {'print $1'}| rev | cut -c -1`
       myCluster=`echo $fullClusterName | awk -F "." {'print $2'}`
     else
       myCluster=$fullClusterName
     fi
   else
     myCluster=$fullClusterName
     ipFlag=true
     
  fi 
#Still there is no distinguish between IP4/ipv6!!!!!!   


  checkHarpoonList

    if [[ $isHarpoon && $myCluster == $fullClusterName ]];then
       accessThrough="mgmt"
       accessThroughNum=""
    elif [[ !($isHarpoon) && $myCluster == $fullClusterName ]];then
       accessThrough="vip"
       accessThroughNum="0"
    fi
  
  

}

connectHarpoon () {

 ###          ROMAN SPECIAL CASE            ###
# if [ $fullClusterName == "172.21.8.200" ];then
#    ssh -nx -p 10022 $userName@$fullClusterName  $commandLine
#    return $?
# fi 
 ##############################################
 if ( $ipFlag );then
       ipFlag=false
       if ( $gsshFlag );then
          ssh -p 10022 $userName@$myCluster $commandLine
       else
          ssh -nx -p 10022 $userName@$myCluster $commandLine
       fi
       return $?
 elif [[  $accessThrough == "vip" || $accessThrough == exadmi* ||  $accessThrough == mgm* ]];then
        if ( $gsshFlag );then
           ssh -p 10022 $userName@mgmt.$myCluster $commandLine
        else
           ssh -nx -p 10022 $userName@mgmt.$myCluster $commandLine
        fi
       return $?
 elif [[  $accessThrough == "node" || `echo $accessThrough` == "ctrl" ]];then
       if ( $gsshFlag );then
         ssh -p 10022 $userName@ctrl${accessThroughNum}.$myCluster $commandLine
       else
         ssh -nx -p 10022 $userName@ctrl${accessThroughNum}.$myCluster $commandLine
       fi
       return $? 
 fi
 
}

connectTopHat (){
  
  if ( $ipFlag );then 
       ipFlag=false 
        if ( $gsshFlag );then
           ssh $userName@$myCluster $commandLine
        else
           ssh -nx $userName@$myCluster $commandLine 
        fi
       return $?
  elif [[ $accessThrough == "vip" || $accessThrough == exadmi*  ||  $accessThrough == mgm* ]];then
        if ( $gsshFlag );then
          ssh $userName@vip0.$myCluster $commandLine
        else
          ssh -nx $userName@vip0.$myCluster $commandLine
        fi
        return $?
  elif [[ $accessThrough == "node" ||  $accessThrough == "ctrl" ]];then
        if ( $gsshFlag );then
          ssh $userName@node${accessThroughNum}.$myCluster $commandLine
        else 
          ssh -nx $userName@node${accessThroughNum}.$myCluster $commandLine
        fi
        return $?
  fi
 
}

excecution () {

  parseClusterName
  if ( $isHarpoon ); then
    ###                            ROMAN SPECIAL CASE                        ####
#    if [[ $fullClusterName == "a8" || $fullClusterName == mgmt.a8 ||  $fullClusterName == vip0.a8 || $fullClusterName == exadmin.a8 ]];then 
 #    fullClusterName="172.21.8.200";
 #   fi
    # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
    
    connectHarpoon $myCluster $commandLine
    return $?
  else
    connectTopHat $myCluster $commandLine
     return $?
  fi
}

checkHarpoonList () {

 #This piece runs  in order to Verify it's an Harpoon
 pingerCounter=1
 touch /dev/shm/harpoonList
 touch /dev/shm/topHatList
while [ $pingerCounter -gt 0 ]; do
  
  if ($(cat /dev/shm/harpoonList | grep $myCluster &> /dev/null));then 
      #echo "You are trying to access Harpoon !!!"
      #echo "Accessing through port 10022"
      isHarpoon=true
      pingerCounter=$((pingerCounter-1));
  elif ($(cat /dev/shm/topHatList | grep $myCluster &> /dev/null));then
      #echo "You are trying to access TopHat / Linux !!!"
      #echo "Accessing through port 22"
      isHarpoon=false
      pingerCounter=$((pingerCounter-1));
  else      
      pingerCounter=$((pingerCounter-1));
      checkHarpoon $myCluster 
      exitCode=`echo $?`
      if  [ $exitCode == 0 ] ;then
        #echo "You are trying to access Harpoon!!!"
        #echo "Accessing through port 10022"
        isHarpoon=true
      elif [ $exitCode == 1 ];then 
        #echo "You are trying to access TopHat / Linux !!!"
        #echo "Accessing through port 22"
        isHarpoon=false
      elif [ $exitCode == 2 ];then
        echo "Cannot detect platform!!!"
        echo "Exiting..."
        exit 1 
      fi
  fi
done
}

checkHarpoon() {
  
   ######Need To add fix for MagicHat#####

   myCluster=$1
   #ping -c 1 $myCluster &> /dev/null
   #arp -a | grep $myCluster | grep "mgmt\|ctrl" | grep "44:a8:42" &> /dev/null
   eth=`ip -o addr  |grep UP | grep eth | awk {'print $2'} | head -1 | cut -d ":" -f1`
   myMac=$( { arping -c 2 $myCluster -I $eth | grep ":" | awk {'print $5'}; }  2> /dev/null)
   if [[ $myMac == "" ]]; then
      return 2
   elif [[ $myMac ==  *"44:A8:42"* || $myMac == *"52:54:00"* || $(nc -z $myCluster 10022 &> /dev/null) ]] ;then
       harpoonList="$harpoonList $myCluster"
       echo $harpoonList >> /dev/shm/harpoonList
       return 0
   #arp -a | grep $myCluster | grep "vip\|node\|exadmin" | grep "a0:36:9f" &> /dev/null
   elif [[ $myMac == *"A0:36:9F"*  || !($(nc -z $myCluster 10022 &> /dev/null)) ]] ;then 
      topHatList="$topHatList $myCluster"
      echo $topHatList >> /dev/shm/topHatList
      return 1
   fi
}

convertHarpoon() {

  fullClusterName=$1
  parseClusterName 
  echo "Access through:"
  echo $accessThrough
  if ( $isHarpoon ); then
     if ( $ipFlag );then
       ipFlag=false
       echo "$myCluster"
     elif [[  $accessThrough == vip* || $accessThrough == exadmi* ||  $accessThrough == mgm* ]];then
          echo "mgmt.$myCluster"
     elif [[  $accessThrough == "node" || `echo $accessThrough` == "ctrl" ]];then
         echo "ctrl${accessThroughNum}.$myCluster"
     fi
  else
     if ( $ipFlag );then
       ipFlag=false
       echo "$myCluster"
     elif [[ $accessThrough == vip* || $accessThrough == exadmi*  ||  $accessThrough == mgm* ]];then
         ($(echo /dev/shm/harpoonList | grep $myCluster &> /dev/null))  
          if ($(echo $accessThroughNum | grep [0-9] &> /dev/null));then
              echo  "vip${accessThroughNum}.$myCluster"
          else
              echo  "vip0.$myCluster"
          fi
     elif [[ $accessThrough == "node" ||  $accessThrough == "ctrl" ]];then
          echo "node${accessThroughNum}.$myCluster"
  fi
fi
}
#####################Main######################
  
 # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  if [[ "$BASH_SOURCE" == $0 ]];then
    global_ssh "$*"
  fi
